id: product-timeline
name: AAVE Smart Product Updates
excerpt: Captures timeline of all the major updates
content: Captures timeline of all the major updates
thumbnail: ipfs://QmNd8S5Z9T8cWv95UUjn5fYR1wU8nLWjeHzXoRC5oVcVe8
publishStatus: Live
events:
  - name: Some Event 1
    uuid: event-1
    date: '2022-11-15T20:00:13.043Z'
    excerpt: Excerpt
    content: Some more details
    moreLink: null
  - name: Some Event 2
    uuid: event-2
    date: '2022-10-15T20:00:13.043Z'
    excerpt: Excerpt
    content: Some more details
    moreLink: null
  - name: Some Event 3
    uuid: event-3
    date: '2022-09-15T20:00:13.043Z'
    excerpt: Excerpt
    content: Some more details
    moreLink: null
  - name: Some Event 4
    uuid: event-4
    date: '2022-08-15T20:00:13.043Z'
    excerpt: Excerpt
    content: Some more details
    moreLink: >-
      http://dodao-localhost.academy:3000/timelines/timeline/edit/product-timeline
  - name: Some Event 5
    uuid: event-5
    date: '2022-07-15T20:00:13.043Z'
    excerpt: Excerpt
    content: Some more details
    moreLink: null
admins:
  - admin1
tags:
  - admin1
priority: 60
created: '2022-11-15T20:00:13.043Z'
